language: python
python:
  - "3.6"
  - "3.7"
install:
- pip install --upgrade -r requirements.txt
- # make sure tests run with these minimal requirements
- python setup.py develop
- # run _one_ test file, just to make sure everything imports fine
- py.test -v copt tests/test_proximal_gradient.py
- # the following are only needed for the examples and coverage tests
- pip install pytest-parallel scikit-image coverage pytest-cov scikit-learn h5py Pillow
- py.test --version
script:
- NUMBA_DISABLE_JIT=1 pytest -v --cov=copt --workers auto
after_success: coveralls
cache:
  directories:
    - $HOME/copt_data
