language: python
python:
  - "2.7"
  - "3.3"
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda install anaconda-client
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  # - python setup.py install
script:
- "nosetests -v"